# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3647dbc0-f893-4400-9a55-149f520a7d6a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b8b24e72-9715-475a-acc9-beafdf907d0d".device = "/dev/disk/by-uuid/b8b24e72-9715-475a-acc9-beafdf907d0d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/85C1-4E1F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # 1. Copy the patch to the system's firmware directory.
  #    This ensures the patch is available to the kernel at boot.
  hardware.firmware = [
    (pkgs.runCommandNoCC "legion-audio-patch" {} ''
      mkdir -p $out/lib/firmware
      # Make sure the path to the patch is correct!
      # The path './legion-alc287.patch' assumes the patch is
      # in the same directory as this .nix file.
#      cp ./modules/nixos/legion-alc287.patch $out/lib/firmware/legion-alc287.patch
      cp /home/astrea/nixos-config/modules/nixos/legion-alc287.patch $out/lib/firmware/legion-alc287.patch
    '')
  ];

  # 2. Instruct the 'snd_hda_intel' kernel module to use the patch.
  boot.extraModprobeConfig = ''
    options snd-hda-intel patch=legion-alc287.patch
  '';
# https://gist.github.com/felipelalli/6179aac72735fd35ea3a9854beb490e5
}
